//! The `wasmtime-wasm2c` crate is an adapter to support files generated by wasm2c.

pub mod adapt;

use wasmtime::Linker;

/// The wasm2c state here
pub struct State {
    /// The instance we allocated when instantizing the wasm2c module
    instance: *const (),
}

impl State {
    pub fn instantiate(lib: &libloading::Library) {}
}

pub fn add_wasm2c_lib<T>(linker: Linker<T>) {}
